### ISSUE TITLE
PowerShell Gallery module missing DSC resources?

### ISSUE THREAD

**Issue by gregjhogan** [PowerShell/xChrome#11]
If I install the xChrome module into an Azure Automation DSC instance (from the gallery) and attempt to use it to install Chrome as described [here](https://github.com/PowerShell/xChrome#install-the-chrome-browser) Azure DSC automation fails to compile the configuration because it can't find MSFT_xChrome.  It looks like there is something wrong with the contents of what is in the PowerShell gallery because it does not list any "DSC Resources" on the summary page in the gallery.

For example:
[xChrome does not list DSC Resources and module does not work](https://www.powershellgallery.com/packages/xChrome/1.0.2.0)
[xFirefox does not list DSC Resources and module does not work](http://www.powershellgallery.com/packages/xFirefox/1.0.0)
[cChoco does list DSC Resources and module does work](https://www.powershellgallery.com/packages/cChoco/2.0.5.22)

**Comment by gregjhogan** [comment]
Here is my example configuration that I load into Azure DSC Automation:

``` javascript
Configuration Sample_InstallChromeBrowser
{
    Import-DscResource -module xChrome

    Node WebBrowser
    {
        MSFT_xChrome chrome
        {
            Language = 'en-US'
            LocalPath = 'C:\Windows\DtlDownloads\GoogleChromeStandaloneEnterprise.msi'
        }
    }
}
```

and here is the exception that I get:

> The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The module 'MSFT_xChrome' could not be loaded. For more information, run 'Import-Module MSFT_xChrome'.

The command 'Import-Module MSFT_xChrome' of course doesn't actually work, and I have installed xChrome using the gallery browse/install feature from the Azure portal.

**Comment by kwirkykat** [comment]
Do you have [xPSDesiredStateConfiguration](https://www.powershellgallery.com/packages/xPSDesiredStateConfiguration/3.9.0.0) loaded into your Azure Automation? Both xChrome and xFirefox are missing the dependency on this module right now (#10). Neither will work if you don't have the xPSDesiredStateConfiguration available for the resources to import.

**Comment by gregjhogan** [comment]
Loading the [xPSDesiredStateConfiguration](https://www.powershellgallery.com/packages/xPSDesiredStateConfiguration/3.9.0.0) module into my Azure Automation account fixed the issue compiling the configuration.
